Downgrade do dominio pra java 7
caelum/financeiro-grupo-caelum-domain pull request #1
Opened 2018-12-04 12:55 UTC by JoaoHL

2018-12-04 13:00 UTC, asouza reviewed
Chegou a conferir com Sergio a real necessidade... pq se pegarmos o modelo e jogarmos para dentro do sistema, não parece que vamos ter problemas. Mas óbvio que eu posso estar deixando escapar algo aqui hehehe.

2018-12-04 13:31 UTC, JoaoHL reviewed
@asouza então, o Kadu me mostrou que na real, eu tava mexendo na parte errada... era pra mexer no `financeiro-domain`, não no `financeiro` (-_-)
Mas sim, era só pra atualizar o domain mesmo. Tô vendo de fazer o release do JAR pra poder usar  sem dar problema de compatibilidade com os Javas mais atualizados dos outros sistemas. No CaelumWeb quebraria, já que lá é Java 7 e o domain tava usando `stream`/`map`

2018-12-04 16:00 UTC, carlosmuller approved these changes

2018-12-05 15:50 UTC, CassioMasteguim approved these changes

2018-12-05 18:31 UTC, ferrelucas approved these changes

2018-12-06 13:39 UTC, gesleyelois approved these changes

2018-12-06 15:59 UTC, fllsouto approved these changes

2018-12-06 18:37 UTC, sergiolopes requested changes

2018-12-06 18:37 UTC, sergiolopes commented on src/main/java/br/com/caelum/financeiro/domain/Transaction.java
> +			description.concat(p.getDescription());
nao funciona :P
concat devolve uma nova string, que estamos ignorando aqui

e, como sugestao, ao inves de fazer com string, fazer com StringBuilder

2018-12-06 19:09 UTC, JoaoHL commented on src/main/java/br/com/caelum/financeiro/domain/Transaction.java
> +			description.concat(p.getDescription());
@sergiolopes arrumado :)

2018-12-06 19:11 UTC, sergiolopes approved these changes

2018-12-10 13:32 UTC, merged